#:schema node_modules/wrangler/config-schema.json
name = "content-worker"
main = "./index.ts"
compatibility_date = "2024-09-24"
compatibility_flags = ["nodejs_compat"]

[env.local]
name = "content-worker"
routes = []
minify = false
