#:schema node_modules/wrangler/config-schema.json
name = "dispatch-worker"
main = "./index.ts"
compatibility_date = "2024-09-24"
compatibility_flags = ["nodejs_compat"]

[[env.local.dispatch_namespaces]]
binding = "DISPATCHER"
namespace = "local"
